version: '3'
services:
  db:
    image: postgres
    container_name: "dbpos"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: postgres
      DB_HOS: dbpos

  mancala-api:
    image: mancala-api
    container_name: mancala-api
    depends_on:
      - db
    ports:
      - "8080:8080"
